import test from "node:test";import assert from "node:assert/strict";
import {enterpriseRelationshipIntelligence,resolveRelationshipPair} from "../src/lib/command/relationshipIntelligence.ts";
const obs=(observationId,division,evidence)=>({observationId,division,role:"PROSPECT",evidence});
test("verified cross-division email resolves identity",()=>{const a=obs("watch-1","WATCH_BROKERAGE",[{kind:"EMAIL",value:"Client@Example.com",verified:true,evidenceId:"watch-email"}]);const b=obs("realty-1","REALTY",[{kind:"EMAIL",value:" client@example.com ",verified:true,evidenceId:"realty-email"}]);const r=resolveRelationshipPair(a,b);assert.equal(r.state,"VERIFIED");assert.equal(r.canonicalRelationshipKey,"EMAIL:client@example.com");assert.equal(r.requiresHumanReview,false)});
test("name similarity alone never auto-merges",()=>{const a=obs("a","WATCH_BROKERAGE",[{kind:"NAME",value:"Jordan Lee",verified:true,evidenceId:"a-name"}]);const b=obs("b","CAPITAL_ADVISORY",[{kind:"NAME",value:"Jordan   Lee",verified:true,evidenceId:"b-name"}]);const r=resolveRelationshipPair(a,b);assert.equal(r.state,"POSSIBLE");assert.equal(r.canonicalRelationshipKey,null);assert.equal(r.requiresHumanReview,true)});
test("unverified contact evidence cannot resolve identity",()=>{const a=obs("a","WATCH_BROKERAGE",[{kind:"PHONE",value:"404-555-0100",verified:false,evidenceId:"a-phone"}]);const b=obs("b","REALTY",[{kind:"PHONE",value:"4045550100",verified:false,evidenceId:"b-phone"}]);assert.equal(resolveRelationshipPair(a,b).state,"UNKNOWN")});
test("conflicting verified evidence requires review",()=>{const a=obs("a","WATCH_BROKERAGE",[{kind:"SOURCE_ID",value:"crm-42",verified:true,evidenceId:"a-source"},{kind:"EMAIL",value:"one@example.com",verified:true,evidenceId:"a-email"}]);const b=obs("b","CAPITAL_ADVISORY",[{kind:"SOURCE_ID",value:"crm-42",verified:true,evidenceId:"b-source"},{kind:"EMAIL",value:"two@example.com",verified:true,evidenceId:"b-email"}]);const r=resolveRelationshipPair(a,b);assert.equal(r.state,"CONFLICT");assert.equal(r.canonicalRelationshipKey,null);assert.equal(r.requiresHumanReview,true)});
test("empty input is honest zero-state",()=>assert.deepEqual(enterpriseRelationshipIntelligence([]),[]));
test("reruns are deterministic regardless of input order",()=>{const a=obs("a","WATCH_BROKERAGE",[{kind:"EMAIL",value:"x@example.com",verified:true,evidenceId:"a-email"}]);const b=obs("b","REALTY",[{kind:"EMAIL",value:"x@example.com",verified:true,evidenceId:"b-email"}]);const c=obs("c","GROWTH",[{kind:"NAME",value:"X Person",verified:true,evidenceId:"c-name"}]);assert.deepEqual(enterpriseRelationshipIntelligence([b,c,a]),enterpriseRelationshipIntelligence([a,b,c]))});
